apiVersion: batch/v1
kind: Job
metadata:
  generateName: ${JOB_NAME}-
spec:
  backoffLimit: 0
  template:
    spec:
      nodeSelector:
        role: gpu
      tolerations:
      - key: node.kubernetes.io/gpu
        operator: Exists
        effect: NoSchedule
      restartPolicy: Never
      containers:
      - name: retrain
        image: "${IMAGE}"
        env:
        - name: MODEL_BUCKET
          value: "${MODEL_BUCKET}"
        - name: RETRAIN
          value: "true"
        command: ["bash","-c"]
        args:
        - python retrain.py --output-s3 s3://${MODEL_BUCKET}/models
