# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: ♾️ CICT Pipeline

on:
  workflow_dispatch:          # 手動トリガのみ

permissions:
  id-token: write             # OIDC トークン発行
  contents: read

env:                          # 共通定数
  AWS_REGION:   ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT:  ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_URI:      ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  IMAGE_REPO:   e2e-ai-carla-dev          # ECR リポジトリ名
  TAG:          roach-${{ github.sha }}   # ← 2 ジョブ共通で固定

# ───────────────────────── Build & Push ─────────────────────────P
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 0) ランナーの空き容量を拡張
    - name: Free runner disk
      run: |
        sudo rm -rf /usr/local/lib/android  /opt/ghc  "$AGENT_TOOLSDIRECTORY"
        df -h /

    # 1) ソース取得
    - uses: actions/checkout@v4

    # 2) Buildx セットアップ
    - uses: docker/setup-buildx-action@v3

    # 3) AWS 認証（OIDC）
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region:     ${{ env.AWS_REGION }}

    # 4) ECR ログイン
    - name: Login to ECR
      run: |
        aws ecr get-login-password |
          docker login --username AWS --password-stdin $ECR_URI

    # 5) Build & Push
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/roach/Dockerfile
        push: true
        tags: ${{ env.ECR_URI }}/${{ env.IMAGE_REPO }}:${{ env.TAG }}
        provenance: false
        sbom:       false

# ───────────────────────── Deploy & Retrain ─────────────────────────
  deploy-and-run:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 0) kubectl インストール
    - uses: azure/setup-kubectl@v3
        with:
          version: v1.30.1   # EKS 1.30 に合わせる
          
    # 1) AWS 認証
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region:     ${{ env.AWS_REGION }}

    # kubeconfig 作成（github-actions-role は aws-auth に追加済み）
    - name: Set up kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name   ${{ secrets.CLUSTER_NAME }} \
          --region $AWS_REGION

    # ---------- デプロイ & リトレーニング ----------
    - name: Deploy new image and kick retrain Job
      env:
        IMAGE:        ${{ env.ECR_URI }}/${{ env.IMAGE_REPO }}:${{ env.TAG }}
        MODEL_BUCKET: ${{ secrets.MODEL_BUCKET }}
      run: |
        echo "Deploying image: $IMAGE"

        
        # 二重 AssumeRole を避けるため一旦環境変数を外す
        unset AWS_ROLE_ARN AWS_WEB_IDENTITY_TOKEN_FILE AWS_ROLE_SESSION_NAME

        # Deployment を更新
        envsubst '$IMAGE' < k8s/roach-deployment.yaml | kubectl apply -f -

        # 旧 Job が残っていると apply に失敗するので事前に削除
        kubectl delete job/roach-retrain --ignore-not-found

        # Retrain Job を投入（manifest は固定 name になっている）
        envsubst '$IMAGE $MODEL_BUCKET' < k8s/roach-retrain-job.yaml | kubectl apply -f -

        # 完了待ち（15 分）
        kubectl wait --for=condition=complete job/roach-retrain --timeout=900s

        # ログ取得
        kubectl logs job/roach-retrain